### DISCUSSION TITLE
LDAP configuration

### DISCUSSION THREAD

**Discussion by bovy89** [DependencyTrack/dependency-track#1093] [Q&A] [answered]
Hi, I’m trying to configure LDAP authN/authZ but I'm stuck and is not clear to me if provided filters works at all.

That is an example of a working ldap configuration in another application:

```
  host: ldap.example.com:636
  insecureSkipVerify: false
  bindDN: $ldap.bindDN
  bindPW: $ldap.bindPW
  userSearch:
    baseDN: "ou=People,dc=yyy,dc=zzz"
    filter: "(|(ismemberof=g:internal:ops::*)(ismemberof=g:internal:dev::*))"
    username: uid
    emailAttr: mail
  groupSearch:
    baseDN: "ou=Groups,dc=yyy,dc=zzz"
    filter: "(description=Groups->Internal->*)"
    userAttr: DN
    groupAttr: member
    nameAttr: description
```

Only people with `(|(ismemberof=g:internal:ops::*)(ismemberof=g:internal:dev::*))` attributes can login
Only groups matching filter `(description=Groups->Internal->*)` will be considered

The problem with dtrack is that, if I'm not wrong, users and groups are sharing the same “basedn” config key (usually there be 2 different config keys, baseDN and groups_baseDN, as shown above).

Due to that and in order to retrives groups, I changed basedn to `dc=yyy,dc=zzz` but this lead me to a duplicated username problem (same uid with differente baseDN). To resolve that I tried the following filter: `ALPINE_LDAP_USERS_SEARCH_FILTER=(&(objectClass=CorporateAccount)(uid={SEARCH_TERM}))`: that works using ldap search but is completeley ignored by dtrack.

In order to figure out if ALPINE_LDAP_USERS_SEARCH_FILTER works (while ignoring groups config), I tried the following conf to let people login, but limiting login to `ismemberof=g:infn:sysinfo:dev::*`
```
      - ALPINE_LDAP_ENABLED=true
      - ALPINE_LDAP_SERVER_URL=ldaps://ldap.example.com:636
      - ALPINE_LDAP_BASEDN=ou=People,dc=infn,dc=it # dc=infn,dc=it
      - ALPINE_LDAP_SECURITY_AUTH=simple
      - ALPINE_LDAP_BIND_USERNAME=${LDAP_BIND_USERNAME}
      - ALPINE_LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - ALPINE_LDAP_AUTH_USERNAME_FORMAT=%s
      - ALPINE_LDAP_ATTRIBUTE_NAME=uid
      - ALPINE_LDAP_ATTRIBUTE_MAIL=mail
      - ALPINE_LDAP_USERS_SEARCH_FILTER=(&(ismemberof=g:infn:sysinfo:dev::*)(uid={SEARCH_TERM}))
      - ALPINE_LDAP_USER_PROVISIONING=true
```

Even in this case, ALPINE_LDAP_USERS SEARCH FILTER doesn't seem to works because everyone, despite the ismemberof attribute, can login

Can you help me to find if I'm doing something wrong?
