### DISCUSSION TITLE
How to setup OIDC with Azure AD?

### DISCUSSION THREAD

**Discussion by cmenzi** [DependencyTrack/dependency-track#1104] [Q&A]
We trying to setup dependency track with Azure AD. We encountered several issues during setup, where we found a workaround by some them.

1. Reply-Url with wildcards `*` is not supported by Azure AD
    1. We just added the following url: `https://dependencytrack.example.com/static/oidc-callback.html?redirect=%2fdashboard`. With this value the token gets passed to dependency track

So after successful receiving the token, we always get an `Invalid username or password` and `Unauthorized (401)`.

What do we need configure on Azure AD and Dependency Track to make it work?

**Comment by nscuro** [comment]
Hi @cmenzi, could you provide the Dependency-Track and AzureAD configurations that you're using? 

If you're getting a 401, DT wasn't able to access AzureAD's `/userinfo` endpoint with the access token acquired during login. You should see this in the DT server logs as well as in AzureAD's logs.

That being said, you'll find that team synchronization doesn't currently work with AzureAD / Microsoft Identity. This limitation has already been resolved though and will be available with Dependency-Track v4.3.0: https://github.com/DependencyTrack/dependency-track/issues/1008

**Reply by cmenzi** [reply]
Hi @nscuro 

We managed it to make it work! The issue was not at Azure side. We now used `email` as `ALPINE_OIDC_USERNAME_CLAIM`. 

But maybe for other here our `docker-compose.yml` for Azure:

```yaml
version: '3.3'

#####################################################
# This Docker Compose file contains three services
#    Dependency-Track API Server
#    Dependency-Track FrontEnd
#    Dependency-Track Database
#####################################################

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:4.3.6
    depends_on:
      - db
    environment:
    # The Dependency-Track container can be configured using any of the
    # available configuration properties defined in:
    # https://docs.dependencytrack.org/getting-started/configuration/
    # All properties are upper case with periods replaced by underscores.
    #
    # Database Properties
    - ALPINE_DATABASE_MODE=external
    - ALPINE_DATABASE_URL=jdbc:postgresql://db:5432/dtrack
    - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
    - ALPINE_DATABASE_DRIVER_PATH=/extlib/postgresql-42.2.18.jar
    - ALPINE_DATABASE_USERNAME=dtrack
    - ALPINE_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    # - ALPINE_DATABASE_POOL_ENABLED=true
    # - ALPINE_DATABASE_POOL_MAX_SIZE=20
    # - ALPINE_DATABASE_POOL_MIN_IDLE=10
    # - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=600000
    # - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
    #
    # Optional LDAP Properties
    # - ALPINE_LDAP_ENABLED=
    # - ALPINE_LDAP_SERVER_URL=ldap://ldap.example.com:389
    # - ALPINE_LDAP_BASEDN=dc=example,dc=com
    # - ALPINE_LDAP_SECURITY_AUTH=simple
    # - ALPINE_LDAP_BIND_USERNAME=
    # - ALPINE_LDAP_BIND_PASSWORD=
    # - ALPINE_LDAP_AUTH_USERNAME_FORMAT=%s@example.com
    # - ALPINE_LDAP_ATTRIBUTE_NAME=userPrincipalName
    # - ALPINE_LDAP_ATTRIBUTE_MAIL=mail
    # - ALPINE_LDAP_GROUPS_FILTER=(&(objectClass=group)(objectCategory=Group))
    # - ALPINE_LDAP_USER_GROUPS_FILTER=(member:1.2.840.113556.1.4.1941:={USER_DN})
    # - ALPINE_LDAP_GROUPS_SEARCH_FILTER=(&(objectClass=group)(objectCategory=Group)(cn=*{SEARCH_TERM}*))
    # - ALPINE_LDAP_USERS_SEARCH_FILTER=(&(objectClass=user)(objectCategory=Person)(cn=*{SEARCH_TERM}*))
    # - ALPINE_LDAP_USER_PROVISIONING=false
    # - ALPINE_LDAP_TEAM_SYNCHRONIZATION=false
    #
    # Optional OpenID Connect (OIDC) Properties
    - ALPINE_OIDC_ENABLED=true
    - ALPINE_OIDC_ISSUER=https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0
    - ALPINE_OIDC_CLIENT_ID=00000000-0000-0000-0000-000000000000
    - ALPINE_OIDC_USERNAME_CLAIM=email
    # - ALPINE_OIDC_TEAMS_CLAIM=groups
    - ALPINE_OIDC_USER_PROVISIONING=true
    # - ALPINE_OIDC_TEAM_SYNCHRONIZATION=true
    #
    # Optional HTTP Proxy Settings
    # - ALPINE_HTTP_PROXY_ADDRESS=proxy.example.com
    # - ALPINE_HTTP_PROXY_PORT=8888
    # - ALPINE_HTTP_PROXY_USERNAME=
    # - ALPINE_HTTP_PROXY_PASSWORD=
    # - ALPINE_NO_PROXY=
    #
    # Optional Cross-Origin Resource Sharing (CORS) Headers
    # - ALPINE_CORS_ENABLED=true
    # - ALPINE_CORS_ALLOW_ORIGIN=*
    # - ALPINE_CORS_ALLOW_METHODS=GET POST PUT DELETE OPTIONS
    # - ALPINE_CORS_ALLOW_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
    # - ALPINE_CORS_EXPOSE_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
    # - ALPINE_CORS_ALLOW_CREDENTIALS=true
    # - ALPINE_CORS_MAX_AGE=3600
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8080'
    volumes:
      - '/datadrive/data/dependency-track/data:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:4.3.1
    depends_on:
      - dtrack-apiserver
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=https://sandbox-dependency-track.alm.buhlergroup.com
      - OIDC_ISSUER=https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0
      - OIDC_CLIENT_ID=00000000-0000-0000-0000-000000000000
      #- OIDC_SCOPE=
      #- OIDC_FLOW=
      # volumes:
      # - "/host/path/to/config.json:/app/static/config.json"
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=dtrack
    - POSTGRES_DB=dtrack
    image: 'postgres:10'
    restart: always
    ports:
    - 5432:5432
    volumes:
      - /datadrive/data/dependency-track/postgresql/data:/var/lib/postgresql/data
```

We don't do group sync/mappings. To we just set `User Assignment required` on the Azure Enterprise Application to `true`. So, people needs to be assigned to the App first. They get automatically added to dependency track and an admin need to assign them manually to a specific Team.

But we are happy with this for now.
