### DISCUSSION TITLE
default admin doesn't work

### DISCUSSION THREAD

**Discussion by heidricha** [DependencyTrack/dependency-track#2397] [Q&A] [answered]
Hi,

I have been using d-t since a while without severe problems, so I'm not a real beginner
now I'm to install a new instance using the latest version (docker, with docker-compose)

looks like it starts OK, but I cannot login as admin/admin

I found no way to change the default user/password in the compose file, or later in the database, so I cannot use the new system at all.

the hosts name is swarm3, I want to connect as http://swarm3:8090

my compose file is:
```
volumes:
  dependency-track:
  database:

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dtrack
      POSTGRES_DB: dtrack
      POSTGRES_PASSWORD: ***
    volumes:
      - database:/var/lib/postgresql/data

  apiserver:
    image: dependencytrack/apiserver:4.7.0
    depends_on:
      - database
    environment:
    - ALPINE_DATABASE_MODE=external
    - ALPINE_DATABASE_URL=jdbc:postgresql://database:5432/dtrack
    - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
    - ALPINE_DATABASE_USERNAME=dtrack
    - ALPINE_DATABASE_PASSWORD=***
    - ALPINE_DATABASE_POOL_ENABLED=true
    - ALPINE_HTTP_PROXY_ADDRESS=10.254.138.80
    - ALPINE_HTTP_PROXY_PORT=8080
    - http_proxy=http://10.254.138.80:8080
    - https_proxy=http://10.254.138.80:8080
    - ALPINE_NO_PROXY=swarm3
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8091:8080'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:4.7.0
    depends_on:
      - apiserver
    environment:
      - API_BASE_URL=http://swarm3:8090
    ports:
      - "8090:8080"
    restart: unless-stopped
```
I get 405 when try to login with admin/admin:

```
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:46 +0000] "GET /static/config.json HTTP/1.1" 200 219 "http://swarm3:8090/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:46 +0000] "GET /api/version HTTP/1.1" 200 3769 "http://swarm3:8090/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:46 +0000] "GET /favicon.ico HTTP/1.1" 200 152583 "http://swarm3:8090/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:46 +0000] "GET /fonts/Simple-Line-Icons.0cb0b9c5.woff2 HTTP/1.1" 200 30064 "http://swarm3:8090/css/app.33d1af45.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:46 +0000] "GET /img/dt-logo-vertical-white-text.fe7a49e8.svg HTTP/1.1" 200 19254 "http://swarm3:8090/login?redirect=%2Fdashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:46 +0000] "GET /img/openid-logo.705c93cd.svg HTTP/1.1" 200 7733 "http://swarm3:8090/login?redirect=%2Fdashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
frontend_1   | 10.254.142.18 - - [20/Jan/2023:12:18:51 +0000] "POST /api/v1/user/login HTTP/1.1" 405 559 "http://swarm3:8090/login?redirect=%2Fdashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52" "-"
```
