### DISCUSSION TITLE
DIsplaying data for multiple branches of the same repo

### DISCUSSION THREAD

**Discussion by pentago** [DependencyTrack/dependency-track#2637] [General]
We're planning to implement SBOM generation across all branches of our organization repos.

Since these will be parameterized in Github Actions workflow, something like this below, can DT web UI display data for multiple branches within the same project view somehow via branch selector or similar?

```
      - name: Uploading SBOMs
        uses: DependencyTrack/gh-upload-sbom@v1.0.0
        with:
          autocreate: true
          apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          serverhostname: 'some_domain.com'
          projectname: ${{ github.repository }}
          projectversion: ${{ github.ref_name }}
          bomfilename: sbom.json

```

Thanks!
