### DISCUSSION TITLE
405 Not Allowed with curl

### DISCUSSION THREAD

**Discussion by somera** [DependencyTrack/dependency-track#3750] [General]
Hi,

I can upload an CycloneDX 1.5 XML-BOM in the DT UI. Fine.

But whet I try curl like here https://docs.dependencytrack.org/usage/cicd/ I get always: "405 Not Allowed".

I created a new team:

![image](https://github.com/DependencyTrack/dependency-track/assets/8334250/96fcdce1-9e9e-4e6e-8dca-93051abe4f4a)

```
$ curl -X "POST" 'http://192.168.178.231:7070/api/v1/bom' \
        -H 'X-API-Key: odt_Bn9jVlc63HpRFGdxRVq2i1rjrLU9ZwI9' \
        -H 'Content-Type: multipart/form-data' \
        -F 'projectame=raspi_mail_service' \
        -F 'projectVersion=master' \
        -F 'parentName=raspi_mail_service' \
        -F 'autoCreate=true' \
        -F "bom=@raspi_mail_service-bom.xml"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76137  100   157  100 75980  51866  23.9M --:--:-- --:--:-- --:--:-- 36.3M<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.25.5</center>
</body>
</html>
```

I run v4.11.1 in Docker.

```
...
  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - TZ=Europe/Berlin
      - API_BASE_URL=http://192.168.178.231:7071
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "7070:8080"
    restart: unless-stopped
```

I don't know what is wrong.

**Comment by somera** [comment]
ok, I found that I should use the API_BASE_URL=http://192.168.178.231:7071/api/v1/bom

**Comment by somera** [comment]
ok, this

```
curl -X "POST" "http://192.168.178.231:7071/api/v1/bom" \
     -H 'Content-Type: multipart/form-data' \
     -H 'X-Api-Key: odt_Bn9jVlc63HpRFGdxRVq2i1rjrLU9ZwI9' \
     -F "project=404b5350-658c-49f8-b6cb-816f4ab1e4ca" \
     -F "bom=@raspi_mail_service-bom.xml"
```

works for me.

**Reply by thawzinmyo** [reply]
Hello @somera , now, I installed
 DT on AKS using Helm Chart. I set up with LoadBalancer Type for service. After installation, I can access both API and Frond End from Internet. But, when I try to login to Front End, I can't log it in. There is an error 405 (Not Allowed). I google it and read many blogs but they did not pointed out the solution. Could you share me if you have some solution? I setup apiBaseUrl. Let me share my Helm Chart for testing!! Actually, it's default Chart file. I just added toleration and apiBaseUrl config.
![Dependency_Track_AKS](https://github.com/user-attachments/assets/bc5c12b4-7e45-4b09-bd4b-10d4823aee82)
![Issue](https://github.com/user-attachments/assets/f8c3835f-39a4-4775-9fe3-8ce469a98347)

```
common:
  nameOverride: ""
  fullnameOverride: ""
  image:
    registry: docker.io
    pullSecrets: []
  secretKey:
    createSecret: false
    existingSecretName: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    automount: false

apiServer:
  deploymentType: StatefulSet
  annotations: {}
  image:
    registry: ''
    repository: dependencytrack/apiserver
    tag: ""
    pullPolicy: IfNotPresent
  command: []
  args: []
  resources:
    requests:
      cpu: "2"
      memory: 5Gi
    limits:
      cpu: "4"
      memory: 5Gi
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    capabilities:
      drop:
      - ALL
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  persistentVolume:
    enabled: false
    className: ""
    size: 5Gi
  extraEnvFrom: []
  extraContainers: []
  extraEnv:
    - name: EXTRA_JAVA_OPTIONS
      value: "-Xmx2g"
    - name: SYSTEM_REQUIREMENT_CHECK_ENABLED
      value: "false"
  tolerations:
    - key: "internal"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  probes:
    liveness:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    readiness:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
  additionalVolumeMounts: []
  additionalVolumes: []
  service:
    type: LoadBalancer
    nodePort: ~
    annotations: {}
  serviceMonitor:
    enabled: false
    namespace: monitoring
    scrapeInternal: 15s
    scrapeTimeout: 30s
  initContainers: []
  nodeSelector: {}

frontend:
  replicaCount: 1
  annotations: {}
  image:
    registry: ''
    repository: dependencytrack/frontend
    tag: ""
    pullPolicy: IfNotPresent
  command: []
  args: []
  resources:
    requests:
      cpu: 150m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
  securityContext:
    capabilities:
      drop:
      - ALL
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
    seccompProfile:
      type: RuntimeDefault
  extraEnv: []
    - name: EXTRA_JAVA_OPTIONS
      value: "-Xmx2g"
    - name: SYSTEM_REQUIREMENT_CHECK_ENABLED
      value: "false"
    - name: API_BASE_URL
      value: "http://my_public_ip:8080"
  extraEnvFrom: []
  extraContainers: []
  tolerations:
    - key: "internal"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  probes:
    liveness:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    readiness:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
  additionalVolumeMounts: []
  additionalVolumes: []
  service:
    type: LoadBalancer
    nodePort: ~
    annotations: {}
  apiBaseUrl: "my_public_ip:8080"
  initContainers: []
  nodeSelector: {}

ingress:
  enabled: false
  annotations: {}
  hostname: "example.com"
  ingressClassName: ""
  tls: []
extraObjects: []
```
