### DISCUSSION TITLE
Configure Load Balancer for  DT deployed on GCE

### DISCUSSION THREAD

**Discussion by spawar-apex** [DependencyTrack/dependency-track#3807] [Q&A] [answered]
Hi, 

I have deployed Dependency track using docker compose ([deploying on docker container](https://docs.dependencytrack.org/getting-started/deploy-docker/)) on a Google Compute Engine. Currently, I have used external ip (`http` protocol) of the Google Compute Engine (GCE VM) in CI/CD pipeline to upload BOM to the project in DT.

I would like to set an Global load balancer in GCP which has public IP with SSL configured (protocol `https` and port `443`). 

How would I configure docker compose (frontend + API backend) to use Load balancer URL. At the moment, both the API server & Frontend are hosted on Same VM so even If I configure Load balancer with SSL, how would I use the `https` domain in Github Actions. 

Here is the Github Action used (From point 1):

```
- name: Upload BOM to Dependency-Track
        # You may pin to the exact commit or the version.
        # uses: DependencyTrack/gh-upload-sbom@5b797334a759f72f780daa0293681cf87a7d9929
        uses: DependencyTrack/gh-upload-sbom@v2.0.0
        continue-on-error: true
        with:
          # Dependency-Track hostname
          serverhostname: '<public_ip)'
          # Dependency-Track port
          port: 8081 # optional, default is 443
          # Dependency-Track protocol
          protocol: 'http' # optional, default is https
          # Dependency-Track API key
          apikey: ${{ secrets.APIKEY }}
          # Project in Dependency-Track
          project: '5948fff8-f26c-4248-876e-90748d832ac8' # optional
          # Project name in Dependency-Track
          projectname: 'source_monorepo' # optional
          # Project version in Dependency-Track
          autoCreate: true
          projectversion: 'v1'   # optional
          # Path and filename of the BOM
          bomfilename: /tmp/sbom.cyclonedx.json # optional, default is bom.xml
```
Can I deploy `Frontend` & `API Server` on Seperate VM's? 

Also, How can I use the subdomain that is mapped to external IP of VM (that runs both the components)?

Any guidance would be appreciated. Thanks!
