### DISCUSSION TITLE
Running DT with containers and PostgreSQL - Need to some basic setup guidance

### DISCUSSION THREAD

**Discussion by nigellh** [DependencyTrack/dependency-track#3955] [Q&A] [answered]
Hi, I have never used PsotgreSQL so complete newbie from that point of view. Or current method of running DT is basically the curl command to get the docker-compose.yml file, tweak the localhost to the server address to allow remote access and docker compose up-d. Works great.

Unfortunately, that uses the H2 database and every couple of months it corrupts and I have to rebuild from scratch.

I have no idea how to get DT working with PostrgreSQL. The documentation (from my point of view) is thin, particularly from a PostgreSQL newbie point of view.

- Is PostgreSQL in the DT containers? 
- Do I just need to enable it?
- Is there a yaml file with it all set up?

Hoping someone can help as I really do not want to have to keep rebuilding it from scratch and I am the only one that knows how! It is not technically a production system, but I have a good number of people who use it for looking at vulnerabilities.

**Comment by nscuro** [comment]
You can take inspiration from the setup we use for testing during development:

* https://github.com/DependencyTrack/dependency-track/blob/master/dev/docker-compose.yml
* https://github.com/DependencyTrack/dependency-track/blob/master/dev/docker-compose.postgres.yml

Merge them into one file and it should be good to go:

```yml
services:
  apiserver:
    image: dependencytrack/apiserver:4.11.5
    depends_on:
    - postgres
    environment:
      ALPINE_DATABASE_MODE: "external"
      ALPINE_DATABASE_URL: "jdbc:postgresql://postgres:5432/dtrack"
      ALPINE_DATABASE_DRIVER: "org.postgresql.Driver"
      ALPINE_DATABASE_USERNAME: "dtrack"
      ALPINE_DATABASE_PASSWORD: "dtrack"
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - "apiserver-data:/data"
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:4.11.5
    environment:
      API_BASE_URL: "http://localhost:8080"
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "dtrack"
      POSTGRES_USER: "dtrack"
      POSTGRES_PASSWORD: "dtrack"
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  apiserver-data: { }
  postgres-data: { }
```

Some instructions for PostgreSQL specific configuration are here: https://dependencytrack.github.io/hyades/latest/operations/database/#basic-configuration

For a small installation you should be fine without additional config, but if performance is important to you, you should definitely have a look at that.

**Reply by nigellh** [reply]
@nscuro Thank you, it starts which is fantastic, but stuck. 

When I try to connect the browser on a separate system to http://nlh-scan-24-041.fyre.ibm.com:8080 (using the yml file at the end) I get unable to connect. I did also change ports to remove the IP address in front (as not in the base yml version) but did not make any affect.

Have I missed or messed something?

If I go on to the server browser with localhost:8080 I get, so guessing it is running in someway.

![image](https://github.com/DependencyTrack/dependency-track/assets/12110404/3f5f9212-8fea-473a-a034-db584cd705f7)

```
#####################################################
# This Docker Compose file contains three services
#    Dependency-Track API Server
#    Dependency-Track FrontEnd
#	   Postgres Database
#####################################################

services:
  apiserver:
    image: dependencytrack/apiserver:4.11.5
    depends_on:
    - postgres
    environment:
      ALPINE_DATABASE_MODE: "external"
      ALPINE_DATABASE_URL: "jdbc:postgresql://postgres:5432/dtrack"
      ALPINE_DATABASE_DRIVER: "org.postgresql.Driver"
      ALPINE_DATABASE_USERNAME: "dtrack"
      ALPINE_DATABASE_PASSWORD: "dtrack"
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - "apiserver-data:/data"
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:4.11.5
    environment:
      API_BASE_URL: "http://nlh-scan-24-041.fyre.ibm.com:8081"
    ports:
    - "8081:8080"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "dtrack"
      POSTGRES_USER: "dtrack"
      POSTGRES_PASSWORD: "dtrack"
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  apiserver-data: { }
  postgres-data: { }

```

**Reply by nscuro** [reply]
If you're accessing the deployment from another machine, you need to remove `127.0.0.1:` from the `apiserver` service as well. And you need to change `API_BASE_URL` of the `frontend` service to point to port `8080` instead of `8081`.

I think in the `docker-compose.yml` from the website, `apiserver` is running on port `8081` and `frontend` on `8080`. In the YAML I posted, it's the other way around.

**Reply by nscuro** [reply, marked as answer]
```yaml
services:
  apiserver:
    image: dependencytrack/apiserver:4.11.5
    depends_on:
    - postgres
    environment:
      ALPINE_DATABASE_MODE: "external"
      ALPINE_DATABASE_URL: "jdbc:postgresql://postgres:5432/dtrack"
      ALPINE_DATABASE_DRIVER: "org.postgresql.Driver"
      ALPINE_DATABASE_USERNAME: "dtrack"
      ALPINE_DATABASE_PASSWORD: "dtrack"
    ports:
    - "8080:8080"
    volumes:
    - "apiserver-data:/data"
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:4.11.5
    environment:
      API_BASE_URL: "http://dtrack.example.com:8080"
    ports:
    - "8081:8080"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "dtrack"
      POSTGRES_USER: "dtrack"
      POSTGRES_PASSWORD: "dtrack"
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  apiserver-data: { }
  postgres-data: { }

```
