### DISCUSSION TITLE
the apiserver had troubles connecting to the PSQL

### DISCUSSION THREAD

**Discussion by Najafov007** [DependencyTrack/dependency-track#4120] [Q&A] [answered]
Hello there, I recently wanted to test dtrack and made it run.  We ran it ou openshift with helm chart. Now I want to connect to dbase postgre. that also was deployed on our cluster. How can we connect it?
_Originally posted by @pshakespeare in https://github.com/DependencyTrack/dependency-track/issues/3575#issuecomment-2029102167_

**Comment by nscuro** [comment, marked as answer]
See here for general configuration guidance: https://docs.dependencytrack.org/getting-started/database-support/

Note that for containers, the properties are set via environment variables, as explained here: https://docs.dependencytrack.org/getting-started/configuration/#api-server

If you're using [the Helm chart](https://github.com/DependencyTrack/helm-charts/tree/main/charts/dependency-track), the following should be in your custom `values.yaml`:

```yaml
apiServer:
  extraEnv:
  - name: ALPINE_DATABASE_MODE
    value: "external"
  - name: ALPINE_DATABASE_URL
    value: "jdbc:postgresql://postgres.example.com:5432/dtrack"
  - name: ALPINE_DATABASE_DRIVER
    value: "org.postgresql.Driver"
  - name: ALPINE_DATABASE_USERNAME
    value: "dtrack"
  - name: ALPINE_DATABASE_PASSWORD
    value: "dtrack"
```

Obviously replace the PostgreSQL hostname `postgres.example.com` with the domain or IP address of your Postgres Pod, and change username and password as needed.

If you deployed PostgreSQL in Kubernetes, you should be able to leverage its [service discovery](https://kubernetes.io/docs/concepts/services-networking/service/#dns) via DNS, so something like this:

```
jdbc:postgresql://postgres.your-namespace.svc.cluster.local:5432/dtrack
```

where `your-namespace` is the k8s namespace in which you deployed PostgreSQL.
