### DISCUSSION TITLE
Unable to get the Trivy analyser working

### DISCUSSION THREAD

**Discussion by nigellh** [DependencyTrack/dependency-track#4477] [Q&A]
Hi

I followed the instructions on here https://docs.dependencytrack.org/datasources/trivy/ to add Trivy into the Docker File and used port 8082. It started ok and I have disabled the internal and Sonatype analysers.

I created a project and added a component manually 

Names: krb5
Version: 1.20.1
Purl: pkg:conda/krb5@1.20.1

On saving it and then looking in the logs I get the message:

[TrivyAnalysisTask] No API token provided; Skipping

![image](https://github.com/user-attachments/assets/448e405f-be7e-4942-b081-130a983a7415)

So I added the Base URL and just left the token that was there as it was, guessing (probably incorrectly) that it was the default one.

Do I need to create a specific one or where can I get an API token from.

Many thanks, N

**Comment by nigellh** [comment]
Digging into this a little bit more

```
  trivy:
    image: aquasec/trivy:latest
    command:
    - server
    - --listen
    - :8082
    - --token
    - yourAuthToken
    volumes:
    - "trivy-cache:/root/.cache/trivy"
    restart: unless-stopped
```

Might be feeling a bit dumb. Do I just make up a toke and replace yourAuthToken above and then use that in the Trivy configuration?

I will try it anyway.
