### DISCUSSION TITLE
Losing data when bouncing deptracker server

### DISCUSSION THREAD

**Discussion by mdere-lightfeatherIO** [DependencyTrack/dependency-track#4864] [General]
So there are times when I bounce the server or do a restart on it in my k8s. My data gets reseted - including my admin credentials. I am using an external postgres RDS database and I confirm there are data in it. What can cause this to happen? This restart cause a temporarily blip to stand up a local H2 database?

I followed this - https://docs.dependencytrack.org/getting-started/database-support/

I'm pulling the config from my k8s Secrets 

Values.yaml
```yaml
# External Database Configuration
database:
  external: true
  driver: org.postgresql.Driver
  secretRef:
    name: drone-dtrack-secrets
    urlKey: ALPINE_DATABASE_URL
    usernameKey: ALPINE_DATABASE_USERNAME
    passwordKey: ALPINE_DATABASE_PASSWORD
```
my deployment:
```yaml
      containers:
        - name: apiserver
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ALPINE_APITOKEN_ENABLED
              value: "true"
            - name: ALPINE_DATABASE_MODE
              value: "external"
            - name: ALPINE_DATABASE_DRIVER
              value: {{ .Values.database.driver | quote }}
            - name: ALPINE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretRef.name }}
                  key: {{ .Values.database.secretRef.urlKey }}
            - name: ALPINE_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretRef.name }}
                  key: {{ .Values.database.secretRef.usernameKey }}
            - name: ALPINE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretRef.name }}
                  key: {{ .Values.database.secretRef.passwordKey }}
            - name: ALPINE_CORS_ENABLED
              value: "true"
            - name: ALPINE_CORS_ALLOW_ORIGIN
              value: {{ .Values.apiServer.frontendUrl | quote }}
            - name: ALPINE_CORS_ALLOW_METHODS
              value: "GET,POST,PUT,DELETE,OPTIONS"
            - name: ALPINE_CORS_ALLOW_HEADERS
              value: "Origin,Content-Type,Authorization,X-Requested-With,Content-Length,Accept,X-Api-Key,X-Total-Count"
            - name: ALPINE_CORS_EXPOSE_HEADERS
              value: "Origin,Content-Type,Authorization,X-Requested-With,Content-Length,Accept,X-Api-Key,X-Total-Count"
            - name: ALPINE_CORS_ALLOW_CREDENTIALS
              value: "true"
            - name: ALPINE_CORS_MAX_AGE
              value: "3600"
```
