### DISCUSSION TITLE
OIDC authentication failing with error 400 - "The value must not be null or empty string"

### DISCUSSION THREAD

**Discussion by tyomcha1** [DependencyTrack/dependency-track#5050] [Q&A]
Currently attempting to set up OpenID Connect with Google for Dependency Track, deployed using the Helm chart, and encountering this issue.
When clicking on the OpenID button, the browser is correctly redirected to the Google login page and the user is correctly prompted to choose an account. From there, the browser is briefly redirected to the callback URL (`https://<host>/static/oidc-callback.html`), but afterwards the browser is redirected back to the login page (specifically to `https://<host>/login?redirect=%2Fdashboard`), which gives the following error:
```
{
    "status": 400,
    "title": "Illegal argument provided",
    "detail": "The value must not be null or empty string"
}
```
Checking with the browser's network inspect tool shows that the specific request giving this error is a POST request to `https://<host>/api/v1/user/oidc/login`, with the accessToken and idToken as the payload. I've checked the idToken (by decoding from base 64) and the accessToken (by checking Google's API endpoint for info on it); neither seem to have any null values or empty strings.

I've previously attempted to instead set up OIDC with Dex and ran into the same issue (in fact, I switched to attempting to set it up with Google in an attempt to avoid this issue).

The relevant parts of the values file I'm using to provide the values for the Helm deployment are as follows:

```
apiServer:
  extraEnv:
    - name: ALPINE_OIDC_ENABLED
      value: 'true'
    - name: ALPINE_OIDC_ISSUER
      value: https://accounts.google.com
    - name: APLINE_OIDC_CLIENT_ID
      value: <redacted>
    - name: ALPINE_OIDC_USERNAME_CLAIM
      value: email
    - name: ALPINE_OIDC_USER_PROVISIONING
      value: 'true'
frontend:
  extraEnv:
    - name: OIDC_ISSUER
      value: https://accounts.google.com
    - name: OIDC_CLIENT_ID
      value: <redacted>
    - name: OIDC_FLOW
      value: implicit
```

(omitted are commented-out lines as well as values under ingress configurations)

After upgrading the chart with
```
    - name: LOGGING_LEVEL
      value: DEBUG
```
added to the env values for the API server, the server produces the following logs when trying to log in with OIDC:
```
2025-06-12 15:26:09,213 DEBUG [OidcConfigurationResolver] Fetching OIDC configuration from issuer https://accounts.google.com [requestId=<id>, requestMethod=GET, requestUri=/v1/oidc/available]
2025-06-12 15:26:09,297 DEBUG [OidcConfigurationResolver] Storing OIDC configuration in cache: OidcConfiguration{issuer='https://accounts.google.com', userInfoEndpointUri=https://openidconnect.googleapis.com/v1/userinfo, jwksUri=https://www.googleapis.com/oauth2/v3/certs} [requestId=<id>, requestMethod=GET, requestUri=/v1/oidc/available]
2025-06-12 15:26:09,920 DEBUG [HttpClientPool] Stats: [leased: 0; pending: 0; available: 0; max: 200]
2025-06-12 15:26:14,096 DEBUG [OidcConfigurationResolver] OIDC configuration loaded from cache [requestId=<id>, requestMethod=GET, requestUri=/v1/oidc/available]
2025-06-12 15:26:14,223 DEBUG [OidcConfigurationResolver] OIDC configuration loaded from cache [requestId=<id>, requestMethod=POST, requestUri=/v1/user/oidc/login]
2025-06-12 15:26:14,249 DEBUG [OidcIdTokenAuthenticator] Fetching JWK set from https://www.googleapis.com/oauth2/v3/certs [requestId=<id>, requestMethod=POST, requestUri=/v1/user/oidc/login]
2025-06-12 15:26:14,303 DEBUG [OidcIdTokenAuthenticator] Storing JWK set in cache [requestId=<id>, requestMethod=POST, requestUri=/v1/user/oidc/login]
```
As far as I can tell, there are no further logs related to the login attempt.

**Comment by userbradley** [comment]
I was facing this issue, but I found clicking on the link that it should be redirected to, I get this error in the browser console

```
Error: No matching state found in storage
    at oidc-client.min.js:1:67898
```

Which points to this bit of code

```
axios.get("./config.json")
            .then((response) => {
                let config = response.data;

                return new Oidc.UserManager({
                    response_mode: config.OIDC_FLOW === "implicit" ? "fragment" : "query",
                    userStore: new Oidc.WebStorageStateStore(),
                    loadUserInfo: false
                });
            })
            .then((oidcUserManager) => {
                return oidcUserManager.signinRedirectCallback();
            })
            .then((user) => {
                const redirectTo = user.state;
                window.location.href = redirectTo && isUrlSaveForRedirect(redirectTo) ? redirectTo : "../";
            })
            .catch((err) => {
                console.log(err);
            });
```

It's worth making an API request to the server to see if it's not a browser issue. 


I see exactly the same errors you do. Tried in many browsers, same thing.

I double triple checked my config and found that there was some confusion in my config around naming.

For the backend ensure it's as

```yaml
  ALPINE_OIDC_ENABLED: "true"
  ALPINE_OIDC_CLIENT_ID: "<redacted>"
  ALPINE_OIDC_ISSUER: "https://<issuer>"
  ALPINE_OIDC_USERNAME_CLAIM: "preferred_username"
  ALPINE_OIDC_USER_PROVISIONING: "true"
  ALPINE_OIDC_TEAMS_CLAIM: "groups"
  LOGGING_LEVEL: "DEBUG"
  ```

And then the frontend env variables

```yaml
            - name: API_BASE_URL
              value: "https://dep.rg.breadnet.co.uk"
            - name: OIDC_ISSUER
              value: "https://redacted
            - name: OIDC_CLIENT_ID
              value: "redacted"
            - name: OIDC_SCOPE
              value: "openid profile email groups"
            - name: OIDC_LOGIN_BUTTON_TEXT
              value: "breadNET Auth"
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: OIDC_FLOW
              value: ""
```

In my case, my flow is not set to `implicit` as per the docs, as it seems you're using google workspace. 

* https://docs.dependencytrack.org/getting-started/configuration/
* https://docs.dependencytrack.org/getting-started/openidconnect-configuration/#:~:text=Directory%20(tenant)%20ID.-,Google,-API%20server

Since sitting down and really looking in to this, I've managed to get it working.

I am quite the AI skeptic, but I would suggest feeding your config, logs and HTML error to https://deepwiki.com/DependencyTrack/dependency-track which actually helped me spot the missing fields. 

In your case, it's worth making sure that the JWT returned by Google actually does include the `email` field

Apologies, this was a ramble
