### ISSUE TITLE
Unable to connect with external mysql database

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [DependencyTrack/dependency-track#1298]
We have been using Dependency Track v3.8.0 with an external mysql db with no issue.

Recently we have been trying to upgrade to v4.3.6 using the docker-compose instructions mentioned at https://docs.dependencytrack.org/getting-started/deploy-docker/ 

We have tried to run the `docker compose` both with an empty database as well as a filled one (in the second case, after also executing the `3.8.0_to_4.0.0_mysql.sql` script on our db of course). We have also tried to utilize an empty postgres db as well besides mysql.
In all cases, although from the logs it looks like the connection between dependency-track and the database is successful (e.g. it initializes the db and starts downloading nvd files) we cannot login no matter what. 
We receive 405 or 503 HTTP responses, but nothing more precise.

We figured that the db might be causing this issue, because when we try to bring up dependency-track without an external db, it works as expected.

Can you please point us to any direction as to what is causing this problem? 
We can't find any instructions regarding database setup for dependency-track. Our `docker-compose.yml` is presented below.

```
version: '3.7'
networks:
  dependency_track_network: 

services:
  mysql-db:
    image: mysql:5.7.29
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dtdb
      MYSQL_ROOT_HOST: '%'
    ports: 
      - "3306:3306"
    command: ['mysqld', '--sql_mode=ANSI_QUOTES,STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION']
    volumes:
      - mysql-data-2:/var/lib/mysql   
    restart: unless-stopped
    networks:
      - dependency_track_network
      
  dtrack-apiserver:
    image: dependencytrack/apiserver
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:mysql://mysql-db:3306/dtdb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      - ALPINE_DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - ALPINE_DATABASE_DRIVER_PATH=/extlib/mysql-connector-java-8.0.22.jar
      - ALPINE_DATABASE_USERNAME=root
      - ALPINE_DATABASE_PASSWORD=password
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=10
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=600000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
    ports:
      - '8081:8080'
    volumes:
      - dt-data-2:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
    networks:
      - dependency_track_network
    depends_on:
      - mysql-db
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://vm_name.domain.com:8081
    ports:
      - "8080:8080"
    restart: unless-stopped    

volumes:
  dt-data-2:
    driver: local
    driver_opts:
      type: none
      device: /data/dt-data-2
      o: bind
  mysql-data-2:
    driver: local
    driver_opts:
      type: none
      device: /data/mysql-data-2
      o: bind
```
