### ISSUE TITLE
Cannot upgrade from v3.8.0 to latest (v4.3.6)

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [DependencyTrack/dependency-track#1340]
We are currently running Dependency Track v3.8.0 using Docker and an external mysql database v5.7.29, and wish to upgrade to the latest version (currently v4.3.6).
As mentioned in the CHANGELOG here: https://docs.dependencytrack.org/2021/01/03/v4.0.0/, the first thing we did was to execute `3.8.0_to_4.0.0_mysql.sql` against our db and then take a dump of our database. 

However, when trying to upgrade we face the following issues:
- We tried upgrading directly to latest versions (server & frontend) from v3.8.0. We start a new, empty mysql database container as well as the frontend and server containers. Up to this point everything works as expected. Once we import the dump to the empty db, we start receiving `503 Service Unavailable` Errors, and the tool 'loses' its functionality.
- We tried various other combinations of server and frontend versions and they all  have the same result once we import our dump to the database.
- **Working scenario:** The only combination that works so far after the dump import is: `dependencytrack/apiserver:4.0.0` and `dependencytrack/frontend:4.3.0`.

My questions are:
1) Is version upgrade from 3.8.0 to anything > 4.0.0 actually supported, or is it problematic?
2) If the upgrade is supported, then maybe the issue lies somewhere in the migration scipt, thus creating incompatibilities with the v4.0.0 data model?
2) How should one upgrade from 4.0.0 to latest while keeping the database filled with the existing data? When we try to upgrade from 4.0.0 to e.g. 4.1.0 in our working scenario we start receiving `503 Service Unavailable` Errors again.

In case needed, the docker-compose.yml is

```
version: '3.7'

networks:
  dependency_track_network: 

volumes:
  mysql-storage:
    name: mysql-storage
  dt-storage:
    name: dt-storage      

services:
  mysql-db:
    image: mysql:5.7.29
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dtdb
      MYSQL_ROOT_HOST: '%'
    ports: 
      - "3306:3306"
    command: ['mysqld', '--character-set-server=ucs2', '--collation-server=ucs2_general_ci', '--sql_mode=ANSI_QUOTES,STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION']
    volumes:
      - mysql-storage:/var/lib/mysql
   
    restart: unless-stopped
    networks:
      - dependency_track_network
      
  dtrack-apiserver:
    image: dependencytrack/apiserver:4.0.0
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:mysql://mysql-db:3306/dtdb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      - ALPINE_DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - ALPINE_DATABASE_DRIVER_PATH=/extlib/mysql-connector-java-8.0.22.jar
      - ALPINE_DATABASE_USERNAME=user
      - ALPINE_DATABASE_PASSWORD=pass
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=10
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=600000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000 
    ports:
      - '8081:8080'
    volumes:
      - dt-storage:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
    networks:
      - dependency_track_network
    depends_on:
      - mysql-db
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:4.3.0
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://our_domain:8081
    ports:
      - "8082:8080"
    restart: unless-stopped 
```
