### ISSUE TITLE
413 Entity too large error on bom upload of docker installation

### ISSUE THREAD

**Issue by peterkline** [DependencyTrack/dependency-track#2087]
### Current Behavior:
When uploading our BOM file which is currently 2.5MB (Sorry I can't get permission from management to upload it) we get the following response:

```shell
Invoke-RestMethod :

413 Request Entity Too Large
413 Request Entity Too Large
nginx/1.21.6
```

We did not have this problem before (DT v.4.2.0) when running DT within a single container but we started using docker-compose and that split it into the frontend and api, 

### Steps to Reproduce:
Create a simple BOM using
```shell
dotnet-CycloneDX "App.sln" -d -t -o "\boms"
```

### Expected Behavior:
Bom uploads successfully without error.  

### Environment:
  
  - Dependency-Track Version: v4.5.0
  - Distribution:  Docker
  - BOM Format & Version: CycloneDX 1.2
  - Database Server:  H2
  - Browser: Firefox 105.0.2 (64-bit)

### Additional Details:
Yes we do understand we are still using the H2 database as a demo but are moving to something more robust after this is resolved.

 We are not running through a proxy or a load-balancer.

Docker-compose.yml
```yaml
version: '3.7'

#####################################################
# This Docker Compose file contains two services
#    Dependency-Track API Server
#    Dependency-Track FrontEnd
#####################################################

volumes:
  dependency-track:

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    environment:
    - ALPINE_DATA_DIRECTORY=~/.dependency-track
    - ALPINE_DATABASE_MODE=embedded
    - ALPINE_DATABASE_URL=jdbc:h2:~/.dependency-track/db
    - ALPINE_DATABASE_DRIVER=org.h2.Driver
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
      restart_policy:
        condition: on-failure
    ports:
      - '8082:8080'
    volumes:
      - './dt-data:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://10.1.10.2:8082
    ports:
      - "8087:8080"
    restart: unless-stopped
```

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
