### ISSUE TITLE
Server error (0)

### ISSUE THREAD

**Issue by GurdipS5** [DependencyTrack/dependency-track#2938]
### Current Behavior

Hi,
I am using the DTrack docker compose file on Ubuntu 22. I download it using the curl command and change the API server url from localhost to the IP of my server.

However, I can browse to the login ui but get server error (0).

I saw the other threads on this but still no luck.

### Steps to Reproduce

1. Download docker compose file
2. Change API server url to the IP of your local server
3. Attemp to login via UI

### Expected Behavior

Login should succeed.

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
Can you provide your settings / environment variables? The API URL must be reacheable from the browser.

**Comment by Ravinder-coder** [comment]
Please use the below configurations in docker-compose.yml. If you want to use a local docker image. You can change the image URL.

```
name: "dependency-track"

services:
  apiserver:
    image: dependencytrack/apiserver:snapshot #if you want to use local image use local image name with tag.
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - "apiserver-data:/data"
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:snapshot
    environment:
      API_BASE_URL: "http://localhost:8080" #if you want to use local image use local image name with tag.
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

volumes:
  apiserver-data: { }

```
