### ISSUE TITLE
PostgreSQL: dependency-track is taking 19% of CPU with no projects

### ISSUE THREAD

**Issue by somera** [DependencyTrack/dependency-track#3237]
### Current Behavior

I installed DT and I'm using my external PG16. And I see this after init process:

![image](https://github.com/DependencyTrack/dependency-track/assets/8334250/65208a71-0ac8-40e9-8d99-1ed30bdfe03c)

I switched to DEBUG loglevel and I see only this.

![image](https://github.com/DependencyTrack/dependency-track/assets/8334250/905ee55d-ff3e-43c3-a5b8-8eb159431f7c)

This

```
version: '3.7'

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    environment:
      # Database Properties
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://xx.xx.xx.xx:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=xxx
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=10
      - ALPINE_DATABASE_POOL_MIN_IDLE=2
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000

      - LOGGING_LEVEL=DEBUG
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '7071:8080'
    volumes:
      - "/data-files/data/docker/dependency-track:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://192.168.178.30:7071
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "7070:8080"
    restart: unless-stopped
```

is my docker-compose.

### Steps to Reproduce

Just run it and wait for finish the init process.

### Expected Behavior

Less CPU usage in idle. This shoud be ~1% in idle. Not more. I'mcomparing this to other tools which I run on my system.

### Dependency-Track Version

4.9.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

16.x

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported
