### ISSUE TITLE
Trivy analyzer support

### ISSUE THREAD

**Issue by fnxpt** [DependencyTrack/dependency-track#3251]
### Current Behavior

No support for trivy

### Proposed Behavior

Trivy is one of the most performant analysers with really good results.
Dependency track should be able to use it and collect its results

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by fnxpt** [comment]
I’m currently working on this and should have it finalised on the next couple of weeks

**Comment by lustr4** [comment]
Great, I'm waiting for this useful functionality (support of trivy analyzer).

**Comment by fnxpt** [comment]
I saw that issue but didn't want to consider it the same because I'm not building a generic analyzer... the plan for this is to use trivy server and do a similar thing done on snyk

**Comment by nscuro** [comment]
No worries @fnxpt, that's totally fine. Just wanted to have these linked as the other issue explicitly mentions Trivy support :)

**Comment by fnxpt** [comment]
Hey everyone quick update in here.

**Comment by fnxpt** [comment]
I created a PR for backend too... there are still some things that are not working as they should.

- Scans on projects that represent docker images are not retrieving OS vulnerabilities
- Scans on web projects are not working... probably due to empty groups

I still need to update the documention and add tests, but I wanted to share this as soon as possible to receive some feedback since this is my first PR in here.

**Comment by nscuro** [comment]
Thanks @fnxpt, this work is much appreciated.

> Regarding documentation I added a few things, but to be honest I'm really but in writing documentation, if someone would like to help let me know

Without having looked at it in too much detail, it would be good to have a (high-level) description of how this is supposed to be set up. To most it is not obvious that Trivy has a server mode, or what needs to be done to make it work. If we'd have a  step-by-step guide on how to set it up, including commands to launch Trivy, that would be super helpful.

Is there any public documentation on the Trivy API you're using?

**Comment by fnxpt** [comment]
Ok, I will try to add that information... additionally we can put as an option on the docker-compose, what do you think @nscuro .
Regarding the API i couldn't find any documentation I had to check their code. They have 2 types of API. A REST API and a protobuf API.

**Comment by fnxpt** [comment]
All package managers that trivy supports should be supported now, docker is also supported now.
@nscuro - is there any way to generate a snapshot image, I would like to still use the official branch for that but if its not possible I will generate one on my fork.
Next steps: Test and compare the results against trivy, just to see if we are missing something... do a little bit of clean up and then add the missing tests.

**Comment by nscuro** [comment]
@fnxpt I pushed images for your changes here:

```
dependencytrack/apiserver:3259-trivy-integration
dependencytrack/frontend:656-trivy-integration
```

**Comment by fnxpt** [comment]
Thanks @nscuro 

So if someone wants to try it my advice is to use the images above + a container running trivy server.
After that you just need to enable it on the Admin -> Analysers settings by providing the endpoint + token.

**Comment by nscuro** [comment]
The following `docker-compose.yml` can be used for the test setup:

```yml
services:
  apiserver:
    image: dependencytrack/apiserver:3259-trivy-integration
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - "apiserver-data:/data"
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:656-trivy-integration
    environment:
      API_BASE_URL: "http://localhost:8080"
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

  trivy:
    image: aquasec/trivy:latest
    command:
    - server
    - --listen
    - 0.0.0.0:8080
    - --token
    - dummy
    restart: unless-stopped

volumes:
  apiserver-data: { }
```

Trivy should then be configured as follows (token is `dummy`):

<img width="826" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/5693141/aeb926fc-b782-4878-9f04-875e8b5062ae">

I would also recommend to disable OSS Index for the duration of the test, as OSS Index is invoked prior to Trivy and there may be significant overlap in findings. Disabling OSS Index makes it easier to see how many findings Trivy is able to raise.

<img width="826" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/5693141/f9640934-5720-4f61-89e4-aeb3fd811402">
