### ISSUE TITLE
Continuous high disk activity on newly created instance

### ISSUE THREAD

**Issue by druppertbcee** [DependencyTrack/dependency-track#3380]
### Current Behavior

I deployed DependencyTrack 4.9 a couple weeks ago on a Kubernetes/Openshift cluster using the integrated H2 database as a playground/proof-of-concept environment.  The deployment configuration is basic and only includes:
- Environment variables for the http_proxy/https_proxy/no_proxy setting
- containerPort definition
- volumeMounts for: /data on NFS and /opt/java/openjdk/lib/security/cacerts to use internal certificates

After starting and downloading the vulnerability databases, the container pulls 0.3 host CPU as well as a whopping 20MB/s disk activity on the NFS server continuously while no projects/scans/BOM/... are configured. The logs show no scheduled process that could explain this activity. I tried updating the containers to 4.10 but the activity remains identical. 

When investigating the NFS server, the db.mv.db file continuously changes and seems to be the source of the disk activity.
I am aware that H2 is not intended for production use but the database write activity should be comparable, and I don't see any external factors that should explain this load caused by an empty instance.

### Steps to Reproduce

DeploymentConfig
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dependencytrack-api
    name: dependenytrack-api
    namespace: ${APP_NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deployment: dependencytrack-api
  template:
    metadata:
      labels:
        deployment: dependencytrack-api
    spec:
      containers:
      - name: dependencytrack-api
        env:
          - name: http_proxy
            value: MY_PROXY_HERE
          - name: https_proxy
            value: MY_PROXY_HERE
          - name: no_proxy
            value: MY_DOMAINS_HERE
        image: >-
          MY_REGISTRY_HERE/dependencytrack/apiserver:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dependencytrack-api-data
          mountPath: /data
        - name: mycacerts
          mountPath: /opt/java/openjdk/lib/security/cacerts
          subPath: cacerts
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: dependencytrack-api-data
        persistentVolumeClaim:
          claimName: dependencytrack-api-data
      - name: mycacerts
        configMap:
        name: mycacerts
        defaultMode: 420
```

### Expected Behavior

The container should show little to no activity while not executing maintenance tasks and while no workload is provided.

### Dependency-Track Version

4.10.0

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported
