### ISSUE TITLE
Usage of Dependency tracker 4.11.3 getting blockage

### ISSUE THREAD

**Issue by nandu525** [DependencyTrack/dependency-track#3857]
### Organization Name

NA

### Organization Website

/api/version

### How is your organization using Dependency Track?

We are unable to access dependency tracker 4.11.3, in the log entry we see, Synchronizing SPDX license definitions to datastore and stopped. Could you please check and let us know the issue.
Because of this we are unable to see oid connect login option in the dependency website.

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by nandu525** [comment]
2024-06-18 07:01:55,689 INFO [EmbeddedJettyServer] alpine-executable-war v2.2.5 (c3a1a709-acdc-4ca7-96dd-5eaab858ee32) built on: 2024-02-29T20:30:01Z
--
2024-06-18 07:01:57,520 INFO [Config] --------------------------------------------------------------------------------
2024-06-18 07:01:57,522 INFO [Config] CPU Cores:    2
2024-06-18 07:01:57,522 INFO [Config] OS Arch:      amd64
2024-06-18 07:01:57,522 INFO [Config] OS Name:      Linux
2024-06-18 07:01:57,522 INFO [Config] OS Version:   5.15.0-1051-azure
2024-06-18 07:01:57,524 INFO [Config] Java Vendor:  Eclipse Adoptium
2024-06-18 07:01:57,524 INFO [Config] Max Memory:   4.0 GB (4,294,967,296.0 bytes)
2024-06-18 07:01:57,525 INFO [Config] Java Home:    /opt/java/openjdk
2024-06-18 07:01:57,525 INFO [Config] Java Temp:    /tmp
2024-06-18 07:01:57,525 INFO [Config] Java Version: 21.0.3+9-LTS
2024-06-18 07:01:57,526 INFO [Config] --------------------------------------------------------------------------------
2024-06-18 07:01:57,526 INFO [Config] Initializing Configuration
2024-06-18 07:01:57,526 INFO [Config] User Home:    /data/
2024-06-18 07:01:57,526 INFO [Config] User:         dtrack
2024-06-18 07:01:57,527 INFO [Config] Loading application.properties from classpath
2024-06-18 07:01:57,527 INFO [Config] System property alpine.application.properties not specified
2024-06-18 07:01:57,531 INFO [Config] --------------------------------------------------------------------------------
2024-06-18 07:01:57,531 INFO [Config] Application:  Dependency-Track
2024-06-18 07:01:57,531 INFO [Config] Version:      4.11.1
2024-06-18 07:01:57,532 INFO [Config] --------------------------------------------------------------------------------
2024-06-18 07:01:57,532 INFO [Config] --------------------------------------------------------------------------------
2024-06-18 07:01:57,532 INFO [Config] Built-on:     2024-02-29T20:30:01Z
2024-06-18 07:01:57,532 INFO [Config] Built-on:     2024-05-19T16:40:32Z
2024-06-18 07:01:57,532 INFO [Config] Framework:    Alpine
2024-06-18 07:01:57,532 INFO [Config] Version :     2.2.5
2024-06-18 07:01:57,587 INFO [RequirementsVerifier] Initializing requirements verifier
2024-06-18 07:01:57,587 INFO [UpgradeInitializer] Initializing upgrade framework
2024-06-18 07:01:59,593 INFO [PersistenceManagerFactory] Initializing persistence framework
2024-06-18 07:01:59,595 INFO [PersistenceManagerFactory] Creating transactional connection pool
2024-06-18 07:01:59,618 INFO [PersistenceManagerFactory] Creating non-transactional connection pool
2024-06-18 07:02:00,689 INFO [HealthCheckInitializer] Registering health checks
2024-06-18 07:02:00,690 INFO [DefaultObjectGenerator] Initializing default object generator
2024-06-18 07:02:00,691 INFO [DefaultObjectGenerator] Synchronizing permissions to datastore
2024-06-18 07:02:00,860 INFO [DefaultObjectGenerator] Synchronizing SPDX license definitions to datastore

**Comment by nandu525** [comment]
API Container Logs pasting for further reference!

**Comment by fonskip** [comment]
Hi, I know it’s a bit old, but I just ran into the same issue and I think I know what’s going on. My suspicion is that you are using the helm chart and there is a livenessprobe that restarts your container after 45s because the init took to long. Try disabling the livenessprobe and see if it succeeds.

**Comment by abdullahkhawer** [comment]
@fonskip , You suggestion worked.

Increasing `initialDelaySeconds` to `120` in the `livenessProbe` worked.

My configuration to connect `dependency-track` with bitnami `postgresql` is as follows:
```
apiServer:
  extraEnv:
    - name: SYSTEM_REQUIREMENT_CHECK_ENABLED
      value: "false"
    - name: ALPINE_DATABASE_MODE
      value: "external"
    - name: ALPINE_DATABASE_URL
      value: "jdbc:postgresql://postgresql.appdev-dependency-track.svc.cluster.local:5432/postgres"
    - name: ALPINE_DATABASE_DRIVER
      value: "org.postgresql.Driver"
    - name: "ALPINE_DATABASE_USERNAME"
      value: "postgres"
    - name: "ALPINE_DATABASE_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: postgresql
```

 Thanks. 👍
