### ISSUE TITLE
Cannot add user to team , because no team with that name exists

### ISSUE THREAD

**Issue by Juastin** [DependencyTrack/dependency-track#4371]
### Current Behavior

When authentication using OpenID Dependency-Track cannot match the teams that are used in the OpenID Connect Groups.
```
2024-11-12 14:40:12,111 DEBUG [OidcAuthenticationService] ID token profile is complete, proceeding to authenticate
2024-11-12 14:40:12,116 DEBUG [OidcAuthenticationService] The user (Justin.Passchier@redacted.com) authenticated successfully but the account has not been provisioned
2024-11-12 14:40:12,133 DEBUG [AlpineQueryManager] Synchronizing team membership for OpenID Connect user Justin.Passchier@redacted.com
2024-11-12 14:40:12,144 WARN [AlpineQueryManager] Cannot add user Justin.Passchier@redacted.com to team , because no team with that name exists
2024-11-12 14:40:12,147 INFO [UserResource] Successful OpenID Connect login / username: Justin.Passchier@redacted.com / IP Address: ... / User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
```
For some reason there is some sort of whitespace after team?: `Cannot add user ... to team , `

---- 

#### As I see no reason why this shouldn't match, I will explain my current situation.

First off we have an ArgoCD that deploys Dependency Track to our kubernetes cluster. 
To make it work with OpenID we have set these variables to the apiServer and frontend:
```
spec:
  project: default
  source:
    chart: dependency-track
    repoURL: https://dependencytrack.github.io/helm-charts/
    targetRevision: 0.22.0 
    helm:
      valuesObject:
        common:
          secretKey:
            value: redacted
        apiServer:
          extraEnv:
            - name: ALPINE_CORS_ALLOW_ORIGIN
              value: redacted
            - name: ALPINE_DATABASE_MODE
              value: "external"
            - name: ALPINE_DATABASE_DRIVER
              value: "org.postgresql.Driver"
            - name: ALPINE_DATABASE_URL
              value: redacted
            - name: ALPINE_DATABASE_USERNAME
              value: redacted
            - name: ALPINE_DATABASE_PASSWORD
              value: redacted
            - name: ALPINE_OIDC_ENABLED
              value: "true"
            - name: ALPINE_OIDC_CLIENT_ID
              value: redacted
            - name: ALPINE_OIDC_ISSUER
              value: redacted
            - name: ALPINE_OIDC_USERNAME_CLAIM
              value: preferred_username
            - name: ALPINE_OIDC_USER_PROVISIONING
              value: "true"
            - name: ALPINE_OIDC_TEAMS_CLAIM
              value: "groups"
            - name: ALPINE_OIDC_TEAMS_SYNCHRONIZATION
              value: "true"
        frontend:
          apiBaseUrl: redacted
          extraEnv:
            - name: OIDC_CLIENT_ID
              value: redacted
            - name: OIDC_ISSUER
              value: redacted
```

When authentication using the Azure AD Tenant I get the following debug lines:

```
2024-11-12 14:40:12,107 DEBUG [OidcIdTokenAuthenticator] JWK set loaded from cache
2024-11-12 14:40:12,110 DEBUG [OidcIdTokenAuthenticator] ID token claims: {"sub":"...","ver":"2.0","iss":"https:\/\/login.microsoftonline.com\/...\/v2.0","groups":["...","...","64e49923-6824-42f1-b166-bd0c4b34a9ac"],"oid":"...","preferred_username":"Justin.Passchier@redacted.com", ...}
```
Which includes the group claim: `64e49923-6824-42f1-b166-bd0c4b34a9ac`.
These debug lines are followed by the debug lines at the top of the issue.

To match the team in Dependency Track I've set the following settings like the documentation describes:

![Image](https://github.com/user-attachments/assets/13afe756-cbc5-4469-b59b-2bdcc705b9b0)
> Changing the 'Group Name' to the name of the group from Azure AD creates another issue, that has already been brought up in [Issue #3042](https://github.com/DependencyTrack/dependency-track/issues/1488)

Again, this matches the groups claim id originating from the id token from Azure AD.
The user does get added to the OpenID Connect Users, but it does not get added to any teams like the warning describes. 

![Image](https://github.com/user-attachments/assets/14cef256-666e-4f9d-920b-00b9d67ec79c)

This presents the user with a lot of 403 errors when trying to log in, due to the fact the newly logged in user doesn't have any teams associated with him/her. Right now the only fix is getting another user to log in and add the new OpenID user to a team.

----
For the database the following helm chart is being used:
```
spec:
  project: default
  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 16.1.2
```

### Steps to Reproduce

1. Have the setup shown above.
2. Authenticate using the AD and retrieve the JWT token that contains the Group claim that is mapped to the _OpenID Connect Groups_
3. Have a team mapped to the _OpenID Connect Groups_ in _Mapped Teams_
4. Authenticate using the AD and get added to the _OpenID Connect Users_ but not added to a team.

### Expected Behavior

I expect the _OpenID Connect User_ To be added to the team that has the same Group name as the user has in his groups claim in his ID token. Instead of needing to be added to a team by another user with permissions.

### Dependency-Track Version

4.12.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

17.0.0

### Browser

N/A

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported
