### ISSUE TITLE
alpine.enforce.authentication=false produces 404s

### ISSUE THREAD

**Issue by nickwilliams-codynamic** [DependencyTrack/dependency-track#653]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
When setting the alpine.enforce.authentication and authorization properties to false, the webserver returns a 404 response for all URLs.

Additionally setting the propertise as environment variables seems to have no effect (e.g. ALPINE_ENFORCE_AUTHENTICATION still show the login screen)

### Steps to Reproduce:
Set alpine.enforce.authentication to false. Sample docker-compose and properties file below

### Expected Behavior:
The depedencytrack dashboard appears with no login screen prompted

### Environment:
  
  - Dependency-Track Version: latest (digest efc65e702ee1)
  - Distribution: Docker
  - BOM Format & Version: N/A
  - Database Server: H2
  - Browser: Firefox | Google Chrome

### Additional Details:

docker-compose.yaml:
```
version: "3"
services:
  dependency-track:
    image: "owasp/dependency-track"
    command: java -XX:MaxRAMPercentage=90.0 -Dalpine.application.properties=/app/props/application.properties -DdependencyTrack.logging.level=INFO -jar dependency-track-embedded.war -context ${CONTEXT}
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
      - ./props:/app/props/application.properties
```
NOTE: Use all other default properties from https://docs.dependencytrack.org/getting-started/configuration/
props/application.properties
```
############################ Alpine Configuration ###########################
# Optional
# When authentication is enforced, API keys are required for automation, and
# the user interface will prevent anonymous access by prompting for login
# credentials.
alpine.enforce.authentication=false

# Optional
# When authorization is enforced, team membership for both API keys and user
# accounts are restricted to what the team itself has access to. To enforce 
# authorization, the enforce.authentication property (above) must be true.
alpine.enforce.authorization=false
```
