### ISSUE TITLE
Provide environment variable for alpine.application.properties

### ISSUE THREAD

**Issue by luhahn** [DependencyTrack/dependency-track#832]
I'm currently working on a helm-chart which is able to generate a dynamic appliaction.properties file as a secret configMap.
This is way more convinient than using environment variables to configure everything in the container.

However currently there is no easy way to configure -Dalpine.application.properties=/config/application.properties for the docker container.

As a workaround im currently using this approach:

```yaml
env:
   - name: JAVA_OPTIONS
      value: -XX:MaxRAMPercentage=90.0 -Dalpine.application.properties=/config/application.properties
```
The current state of the helm chart can be found here:
https://github.com/novumrgi/helm/tree/master/charts/dependency-track

Which will hopefully be integrated into https://github.com/evryfs/helm-charts once I've finalized the chart.
